//
//  PredefinedData.swift
//  Symptomly
//
//  Created by Bastien Villefort on 6/20/25.
//

import Foundation

struct PredefinedData {
    static let remedyNames = [
    "Aconite",
    "Allium Cepa",
    "Alumina",
    "Antimonium Crudum",
    "Antimonium Tart",
    "Apis Mellifica",
    "Argentum Nitricum",
    "Arnica Montana",
    "Arsenicum Album",
    "Aurum Metallicum",
    "Baryta Carb",
    "Belladonna",
    "Berberis Vulgaris",
    "Borax",
    "Bryonia",
    "Calcarea Carbonica",
    "Calcarea Fluorica",
    "Calcarea Phosphorica",
    "Calendula",
    "Cantharis",
    "Capsicum",
    "Carbo Veg",
    "Causticum",
    "Chamomilla",
    "Chelidonium",
    "China Officinalis",
    "Cimicifuga",
    "Cina",
    "Cocculus Indicus",
    "Coffea Cruda",
    "Colchicum",
    "Colocynthis",
    "Conium",
    "Crotalus Horridus",
    "Cuprum Metallicum",
    "Cyclamen",
    "Digitalis",
    "Dulcamara",
    "Eupatorium Perfoliatum",
    "Euphrasia",
    "Ferrum Phos",
    "Fluoric Acid",
    "Gelsemium",
    "Glonoinum",
    "Graphites",
    "Hamamelis",
    "Hepar Sulph",
    "Hydrastis",
    "Hyoscyamus",
    "Hypericum",
    "Ignatia",
    "Iodium",
    "Ipecacuanha",
    "Kali Bichromicum",
    "Kali Carb",
    "Kali Phos",
    "Kreosotum",
    "Lachesis",
    "Lycopodium",
    "Magnesia Phos",
    "Medorrhinum",
    "Mercurius Solubilis",
    "Moschus",
    "Natrum Carb",
    "Natrum Muriaticum",
    "Natrum Phos",
    "Nitric Acid",
    "Nux Moschata",
    "Nux Vomica",
    "Opium",
    "Paris Quadrifolia",
    "Petroleum",
    "Phosphoric Acid",
    "Phosphorus",
    "Pulsatilla",
    "Pyrogenium",
    "Rhus Toxicodendron",
    "Ruta Graveolens",
    "Sabadilla",
    "Sabina",
    "Sambucus",
    "Sanguinaria",
    "Secale Cornutum",
    "Sepia",
    "Silicea",
    "Spigelia",
    "Spongia Tosta",
    "Staphysagria",
    "Stramonium",
    "Sulphur",
    "Symphytum",
    "Syphilinum",
    "Tabacum",
    "Tarentula",
    "Terebinthina",
    "Thuja Occidentalis",
    "Urtica Urens",
    "Veratrum Album",
    "Viburnum Opulus",
    "Zincum Metallicum"
    ]
} 