//
//  PredefinedData.swift
//  Symptomly
//
//  Created by Bastien Villefort on 6/20/25.
//

import Foundation

struct PredefinedData {
    static let remedyNames = [
        "Abies canadensis",
        "Abies nigra",
        "Abrotanum",
        "Aceticum acidum",
        "Achillea millefolium",
        "Aconitum napellus",
        "Aethusa cynapium",
        "Agaricus",
        "Agaricus muscarius",
        "Agnus castus",
        "Ailanthus glandulosa",
        "Aleurites fordii",
        "Allium cepa",
        "Allium sativum",
        "Aloe socotrina",
        "Alstonia scholaris",
        "Alumina",
        "Ambra grisea",
        "Ammonium carbonicum",
        "Ammonium muriaticum",
        "Anacardium orientale",
        "Anagallis arvensis",
        "Anthracinum",
        "Antimonium arsenicosum",
        "Antimonium crudum",
        "Antimonium sulphuratum aureum",
        "Antimonium tartaricum",
        "Apis mellifica",
        "Apocynum cannabinum",
        "Aquilegia vulgaris",
        "Aralia quinquefolia",
        "Aralia racemosa",
        "Arbutus andrachne",
        "Arctium lappa",
        "Argemone mexicana",
        "Argentum metallicum",
        "Argentum nitricum",
        "Aristolochia clematitis",
        "Arnica montana",
        "Arnotherium",
        "Arsenicum album",
        "Arsenicum iodatum",
        "Artemisia vulgaris",
        "Arum triphyllum",
        "Asafoetida",
        "Asarum europaeum",
        "Asclepias tuberosa",
        "Aspidosperma",
        "Asterias rubens",
        "Atropinum sulphuricum",
        "Aurum metallicum",
        "Avena sativa",
        "Azadirachta indica",
        "Bacillinum",
        "Bambusa",
        "Baptisia tinctoria",
        "Baryta carbonica",
        "Belladonna",
        "Bellis perennis",
        "Benzoicum acidum",
        "Berberis aquifolium",
        "Berberis vulgaris",
        "Betula alba",
        "Bismuthum",
        "Bismuthum subnitricum",
        "Blatta orientalis",
        "Borago officinalis",
        "Borax",
        "Bothrops lanceolatus",
        "Bovista",
        "Brassica napus",
        "Bromium",
        "Bromum",
        "Bryonia alba",
        "Bryophyllum",
        "Bufo rana",
        "Cactus grandiflorus",
        "Cajanus indicus",
        "Caladium seguinum",
        "Calcarea aceticum",
        "Calcarea arsenicosa",
        "Calcarea carbonica",
        "Calcarea fluorica",
        "Calcarea iodata",
        "Calcarea phosphorica",
        "Calendula",
        "Calendula officinalis",
        "Camphora",
        "Camphora bromata",
        "Cannabis indica",
        "Cannabis sativa",
        "Cantharis",
        "Cantharis vesicatoria",
        "Capsicum",
        "Capsicum annuum",
        "Carbo animalis",
        "Carbo vegetabilis",
        "Carcinosinum",
        "Carduus marianus",
        "Castor equi",
        "Caulophyllum thalictroides",
        "Causticum",
        "Cenchris contortrix",
        "Cereus bonplandii",
        "Chamomilla",
        "Chamomilla vulgaris",
        "Chelidonium majus",
        "Chelone glabra",
        "Chenopodium",
        "Chimaphila umbellata",
        "China officinalis",
        "Chininum arsenicosum",
        "Chininum sulphuricum",
        "Chionanthus virginica",
        "Cicuta",
        "Cicuta virosa",
        "Cimex lectularius",
        "Cimicifuga racemosa",
        "Cina",
        "Cineraria maritima",
        "Cistus canadensis",
        "Clematis erecta",
        "Cocculus",
        "Cocculus indicus",
        "Coccus cacti",
        "Cod liver oil",
        "Coffea cruda",
        "Colchicum",
        "Colchicum autumnale",
        "Collinsonia canadensis",
        "Colocynth",
        "Colocynthis",
        "Comocladia dentata",
        "Condurango",
        "Conium",
        "Conium maculatum",
        "Convallaria majalis",
        "Corallium rubrum",
        "Coriaria",
        "Cornus florida",
        "Crocus",
        "Crocus sativus",
        "Crotalus horridus",
        "Croton tiglium",
        "Cubeba",
        "Culex musca",
        "Cuprum aceticum",
        "Cuprum metallicum",
        "Cyclamen",
        "Cyclamen europaeum",
        "Cypripedium",
        "Digitalis",
        "Digitalis purpurea",
        "Dioscorea",
        "Dioscorea villosa",
        "Doryphora",
        "Drosera",
        "Drosera rotundifolia",
        "Dulcamara",
        "Echinacea angustifolia",
        "Elaps corallinus",
        "Ephedra vulgaris",
        "Equisetum hyemale",
        "Erigeron canadensis",
        "Eryngium",
        "Eschscholtzia californica",
        "Eucalyptus globulus",
        "Eugenia jambosa",
        "Eupatorium aromaticum",
        "Eupatorium perfoliatum",
        "Eupatorium purpureum",
        "Euphorbia",
        "Euphrasia",
        "Euphrasia officinalis",
        "Eupion",
        "Fel tauri",
        "Ferrum aceticum",
        "Ferrum metallicum",
        "Ferrum muriaticum",
        "Ferrum phosphoricum",
        "Ferrum picricum",
        "Fluoricum acidum",
        "Formica rufa",
        "Fucus vesiculosus",
        "Gambogia",
        "Gelsemium",
        "Gelsemium sempervirens",
        "Gentiana lutea",
        "Geranium maculatum",
        "Glechoma hederacea",
        "Glonoinum",
        "Glycerinum",
        "Gnaphalium",
        "Graphites",
        "Gratiola officinalis",
        "Guaiacum",
        "Hamamelis",
        "Hamamelis virginiana",
        "Hecla lava",
        "Helianthus",
        "Helleborus",
        "Heloderma",
        "Helonias",
        "Helonias dioica",
        "Hepar sulph",
        "Hepar sulphuris calcareum",
        "Hippomanes",
        "Histaminum",
        "Hydrangea",
        "Hydrastis",
        "Hydrastis canadensis",
        "Hydrocyanicum acidum",
        "Hyoscyamus",
        "Hyoscyamus niger",
        "Hypericum",
        "Hypericum perforatum",
        "Ignatia",
        "Ignatia amara",
        "Indigo",
        "Iodium",
        "Ipecac",
        "Ipecacuanha",
        "Ipomoea",
        "Iris",
        "Iris versicolor",
        "Jaborandi",
        "Jalapa",
        "Juglans cinerea",
        "Juniperus communis",
        "Justicia adhatoda",
        "Kali bichromicum",
        "Kali carbonicum",
        "Kali muriaticum",
        "Kali phosphoricum",
        "Kali sulphuricum",
        "Kalmia latifolia",
        "Kreosotum",
        "Lachesis",
        "Lachesis mutus",
        "Lactuca",
        "Lactuca virosa",
        "Lamium",
        "Lapis albus",
        "Lathyrus sativus",
        "Latrodectus mactans",
        "Laurocerasus",
        "Lecithinum",
        "Ledum",
        "Ledum palustre",
        "Lemna minor",
        "Lilium tigrinum",
        "Lithium carbonicum",
        "Lobelia cardinalis",
        "Lobelia inflata",
        "Lycopodium clavatum",
        "Lycopus virginicus",
        "Magnesia carbonica",
        "Magnesia muriatica",
        "Magnesia phosphorica",
        "Medorrhinum",
        "Mercurius corrosivus",
        "Mercurius solubilis",
        "Mercurius vivus",
        "Mezereum",
        "Moschus",
        "Muriaticum acidum",
        "Natrum carbonicum",
        "Natrum muriaticum",
        "Natrum phosphoricum",
        "Natrum sulphuricum",
        "Nux moschata",
        "Nux vomica",
        "Opium",
        "Oxalic acidum",
        "Palladium metallicum",
        "Paraffinum",
        "Petroleum",
        "Phosphoric acidum",
        "Phosphorus",
        "Phytolacca decandra",
        "Picricum acidum",
        "Piper methysticum",
        "Platina metallicum",
        "Plumbum metallicum",
        "Podophyllum peltatum",
        "Psorinum",
        "Pulsatilla pratensis",
        "Rhus toxicodendron",
        "Ruta graveolens",
        "Sabina",
        "Sambucus nigra",
        "Sanguinaria canadensis",
        "Sarsaparilla",
        "Secale cornutum",
        "Sepia officinalis",
        "Silicea terra",
        "Spigelia anthelmia",
        "Spongia tosta",
        "Stannum metallicum",
        "Staphysagria",
        "Stramonium",
        "Sulphur",
        "Symphytum officinale",
        "Tabacum",
        "Taraxacum officinale",
        "Tarentula hispanica",
        "Tellurium metallicum",
        "Thuja occidentalis",
        "Tuberculinum",
        "Urtica urens",
        "Veratrum album",
        "Viburnum opulus",
        "Viola odorata",
        "Zincum metallicum"
    ]
}
